import os

DAISY_BOILERPLATE_CSS = """/* This file was generated by HABC from style.css */
html { display: block; width: 100%; }
head, head * { display: none; }
body { display: block; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); font-family: arial, verdana, sans-serif; line-height: 1.5em; margin-top: 4em; margin-bottom: 2em; margin-left: 6em; margin-right: 6em; }
.frontmatter, .bodymatter, .rearmatter { display: block; margin-top: 1em; margin-bottom: 1em; }
.doctitle, .docauthor, .covertitle { display: block; font-weight: bold; text-align: center; }
.doctitle { font-size: 2.0em; }
.docauthor { font-style: italic; font-size: 1.5em; }
h1, h2, h3, h4, h5, h6, .levelhd { display: block; font-weight: bold; margin-bottom: 0.5em; }
h1 { font-size: 1.7em; margin-top: 0.8em; }
h2 { font-size: 1.5em; margin-top: 0.7em; }
h3 { font-size: 1.4em; margin-top: 0.6em; }
p { display: block; margin-top: 0.7em; }
.prodnote { display: block; padding: 0.2em; margin: 0.3em; border: 1px solid black; }
.pagenum { display: inline; padding: 0.2em 0.2em 0.2em 1em; border: 1px solid rgb(200, 200, 250); }
"""

def write_boilerplate_css(output_dir: str) -> str:
    """
    Writes the static DAISY/DTBook boilerplate CSS to the specified output directory.
    
    Args:
        output_dir: The target directory where style.css will be written.
        
    Returns:
        The absolute path to the generated style.css file.
    """
    os.makedirs(output_dir, exist_ok=True)
    css_path = os.path.join(output_dir, "style.css")
    with open(css_path, "w", encoding="utf-8") as f:
        f.write(DAISY_BOILERPLATE_CSS)
    return css_path


import xml.etree.ElementTree as ET
from src.utils.time_formatter import format_hindenburg_time

STATIC_TEXT_ITEMS_XML = """<TextItems>
  <TextItem Name="Title" State="1" Key="1">
    <h1 class="docTitle">Title</h1>
  </TextItem>
  <TextItem Name="Author" State="1" Key="2">
    <h1 class="docAuthor">Author(s)</h1>
  </TextItem>
  <TextItem Name="Annotation" State="1" Key="3">
    <h1 class="annotation">Library of Congress Annotation</h1>
  </TextItem>
  <TextItem Name="Close" State="1" Key="4">
    <h1 class="close">Close</h1>
  </TextItem>
  <TextItem Name="H1" State="1" Key="5">
    <h1>Header 1</h1>
  </TextItem>
  <TextItem Name="H2" State="1" Key="6">
    <h2>Header 2</h2>
  </TextItem>
  <TextItem Name="H3" State="1" Key="7">
    <h3>Header 3</h3>
  </TextItem>
  <TextItem Name="H4" Key="8">
    <h4>Header 4</h4>
  </TextItem>
  <TextItem Name="H5" Key="9">
    <h5>Header 5</h5>
  </TextItem>
  <TextItem Name="H6" Key="0">
    <h6>Header 6</h6>
  </TextItem>
  <TextItem Name="Reader's Note" State="1">
    <div class="prodnote">
      <p>Reader's Note</p>
    </div>
  </TextItem>
  <TextItem Name="Segment" State="1">
    <p class="segment">Segment</p>
  </TextItem>
  <TextItem Name="Note-Ref" State="1">
    <a class="noteref">*</a>
  </TextItem>
  <TextItem Name="Note-Content" State="1">
    <div class="note">
      <p>Note content</p>
    </div>
  </TextItem>
  <TextItem Name="Sidebar" State="1">
    <div class="sidebar">
      <p>Sidebar</p>
    </div>
  </TextItem>
  <TextItem Name="Page" State="1">
    <span class="pagenum">#</span>
  </TextItem>
  <TextItem Name="Line" State="0">
    <span class="linenum">#</span>
  </TextItem>
</TextItems>"""

def get_static_text_items() -> ET.Element:
    """
    Returns the static <TextItems> XML element tree block.
    
    Returns:
        An xml.etree.ElementTree.Element representing the root of the TextItems block.
    """
    return ET.fromstring(STATIC_TEXT_ITEMS_XML)


def format_duration_hhmmss_mmm(ms: float) -> str:
    """
    Converts duration in milliseconds to HH:MM:SS.mmm format.
    
    Args:
        ms: Duration in milliseconds.
        
    Returns:
        Formatted time string (HH:MM:SS.mmm).
    """
    total_seconds = int(ms // 1000)
    milliseconds = int(round(ms % 1000))
    if milliseconds >= 1000:
        total_seconds += 1
        milliseconds -= 1000
        
    hours = total_seconds // 3600
    minutes = (total_seconds // 60) % 60
    seconds = total_seconds % 60
    
    return f"{hours:02d}:{minutes:02d}:{seconds:02d}.{milliseconds:03d}"


def generate_audio_pool_node(audio_data: list[dict], project_name: str, output_dir: str) -> ET.Element:
    """
    Dynamically generates the <AudioPool> XML node for an .nhsx file.
    
    Args:
        audio_data: A list of dicts containing 'filename', 'absolute_path', and 'duration' (in ms).
        project_name: The name of the project.
        output_dir: The target output directory.
        
    Returns:
        An xml.etree.ElementTree.Element representing the <AudioPool> node.
    """
    audio_files_dir = os.path.join(output_dir, f"{project_name} Files")
    audio_pool = ET.Element("AudioPool", {
        "Path": f"{project_name} Files",
        "Location": audio_files_dir
    })
    
    for idx, item in enumerate(audio_data, start=1):
        filename = item["filename"]
        abs_path = item["absolute_path"]
        duration_ms = item["duration"]
        
        duration_str = format_hindenburg_time(duration_ms)
        
        ET.SubElement(audio_pool, "File", {
            "Id": str(idx),
            "Name": filename,
            "OriginalPath": abs_path,
            "Duration": duration_str,
            "Leq": "-"
        })
        
    return audio_pool


def generate_tracks_node(audio_data: list[dict]) -> ET.Element:
    """
    Generates the <Tracks> XML node containing a single <Track Name="Narration">
    populated with child <Region> nodes for each audio file.
    
    Args:
        audio_data: List of dicts containing 'filename' and 'duration' (in ms).
        
    Returns:
        An xml.etree.ElementTree.Element representing the <Tracks> node.
    """
    tracks = ET.Element("Tracks")
    track = ET.SubElement(tracks, "Track", {"Name": "Narration"})
    
    cumulative_ms = 0.0
    for idx, item in enumerate(audio_data, start=1):
        filename = item["filename"]
        # Use filename without extension as Region Name
        region_name, _ = os.path.splitext(filename)
        duration_ms = item["duration"]
        
        region_attrs = {
            "Ref": str(idx),
            "Name": region_name,
            "Start": format_hindenburg_time(cumulative_ms),
            "Length": format_hindenburg_time(duration_ms)
        }
        
        ET.SubElement(track, "Region", region_attrs)
        cumulative_ms += duration_ms
        
    return tracks


def _parse_headings(audio_data: list[dict]) -> list[dict]:
    """
    Parses structural heading information from audio_data sequentially.
    
    Returns:
        List of dicts representing headings, each with id, tag, class, text, start_sec.
    """
    import re
    
    headings = []
    id_counter = 1
    last_section = None
    cumulative_seconds = 0.0
    
    for item in audio_data:
        filename = item["filename"]
        duration_sec = (item.get("duration", 0.0) / 1000.0)
        base_name, _ = os.path.splitext(filename)
        clean_name = re.sub(r"^\d{3}\s+", "", base_name).strip()
        
        if "docTitle" in clean_name:
            title_text = clean_name.replace("docTitle", "").strip()
            headings.append({
                "id": f"hix{id_counter:05d}",
                "tag": "h1",
                "class": "docTitle",
                "text": title_text,
                "start_sec": cumulative_seconds
            })
            id_counter += 1
        elif "docAuthor" in clean_name:
            author_text = clean_name.replace("docAuthor", "").strip()
            headings.append({
                "id": f"hix{id_counter:05d}",
                "tag": "h1",
                "class": "docAuthor",
                "text": author_text,
                "start_sec": cumulative_seconds
            })
            id_counter += 1
        elif "annotation" in clean_name:
            annot_text = clean_name.replace("annotation", "").strip()
            headings.append({
                "id": f"hix{id_counter:05d}",
                "tag": "h1",
                "class": "annotation",
                "text": annot_text,
                "start_sec": cumulative_seconds
            })
            id_counter += 1
        else:
            parts = re.split(r"\s+[\u2013\u2014\-]\s+", clean_name, maxsplit=1)
            if len(parts) == 2:
                section_title = parts[0].strip()
                article_title = parts[1].strip()
                
                if section_title != last_section:
                    headings.append({
                        "id": f"hix{id_counter:05d}",
                        "tag": "h1",
                        "class": None,
                        "text": section_title,
                        "start_sec": cumulative_seconds
                    })
                    id_counter += 1
                    last_section = section_title
                    
                headings.append({
                    "id": f"hix{id_counter:05d}",
                    "tag": "h2",
                    "class": "article",
                    "text": article_title,
                    "start_sec": cumulative_seconds
                })
                id_counter += 1
            else:
                headings.append({
                    "id": f"hix{id_counter:05d}",
                    "tag": "h1",
                    "class": "article",
                    "text": clean_name,
                    "start_sec": cumulative_seconds
                })
                id_counter += 1
                
        cumulative_seconds += duration_sec
        
    return headings


def generate_document_xhtml(audio_data: list[dict], metadata: dict, output_dir: str) -> str:
    """
    Generates the structural Document.xhtml file using xml.etree.ElementTree.
    
    Args:
        audio_data: List of dicts containing 'filename'.
        metadata: Dict containing project metadata.
        output_dir: The target output directory where Document.xhtml will be written.
        
    Returns:
        The absolute path to the generated Document.xhtml file.
    """
    ET.register_namespace("", "http://www.w3.org/1999/xhtml")
    ET.register_namespace("epub", "http://www.idpf.org/2007/ops")
    
    html = ET.Element("html", {
        "xmlns": "http://www.w3.org/1999/xhtml",
        "xmlns:epub": "http://www.idpf.org/2007/ops",
        "xml:lang": "en",
        "lang": "en"
    })
    
    head = ET.SubElement(html, "head")
    ET.SubElement(head, "title").text = metadata.get("title", "")
    ET.SubElement(head, "meta", {"name": "dc:title", "content": metadata.get("title", "")})
    ET.SubElement(head, "meta", {"name": "dc:creator", "content": metadata.get("creator", "")})
    ET.SubElement(head, "meta", {"name": "dc:identifier", "content": metadata.get("identifier", "")})
    ET.SubElement(head, "meta", {"name": "dc:format", "content": " "})
    ET.SubElement(head, "meta", {"name": "dc:publisher", "content": metadata.get("publisher", "National Library Service for the Blind and Print Disabled, Library of Congress")})
    ET.SubElement(head, "meta", {"name": "ncc:generator", "content": metadata.get("generator", "Hindenburg ABC Studio 1.60")})
    ET.SubElement(head, "link", {"rel": "stylesheet", "type": "text/css", "href": "style.css"})
    ET.SubElement(head, "meta", {"charset": "UTF-8"})
    
    body = ET.SubElement(html, "body")
    
    headings = _parse_headings(audio_data)
    for i, h in enumerate(headings):
        attrs = {"id": h["id"]}
        if i == 0:
            attrs["class"] = "docTitle"
        elif h["class"]:
            attrs["class"] = h["class"]
            
        elem = ET.SubElement(body, h["tag"], attrs)
        elem.text = h["text"]
                
    os.makedirs(output_dir, exist_ok=True)
    xhtml_path = os.path.join(output_dir, "Document.xhtml")
    
    tree = ET.ElementTree(html)
    ET.indent(tree, space="  ", level=0)
    with open(xhtml_path, "wb") as f:
        f.write(b'<?xml version="1.0" encoding="UTF-8"?>\n')
        tree.write(f, encoding="UTF-8", xml_declaration=False, method="xml")
    
    return xhtml_path


def generate_nav_points_node(audio_data: list[dict]) -> ET.Element:
    """
    Generates the <NavPoints> XML block for the .nhsx document,
    containing two <NavPoint> elements per heading to define boundaries.
    
    Args:
        audio_data: List of dicts containing 'filename' and 'duration' (in ms).
        
    Returns:
        An xml.etree.ElementTree.Element representing the <NavPoints> node.
    """
    headings = _parse_headings(audio_data)
    nav_points = ET.Element("NavPoints")
    
    for h in headings:
        start_ms = h["start_sec"] * 1000.0
        end_ms = start_ms + 3000.0  # Add exactly 3.000s placeholder offset
        
        begin_str = format_hindenburg_time(start_ms)
        end_str = format_hindenburg_time(end_ms)
        
        # ClipBegin boundary
        ET.SubElement(nav_points, "NavPoint", {
            "Id": h["id"],
            "Begin": begin_str
        })
        # ClipEnd boundary (placeholder)
        ET.SubElement(nav_points, "NavPoint", {
            "Id": h["id"],
            "Begin": end_str
        })
        
    return nav_points


def compile_hindenburg_session(audio_data: list[dict], metadata: dict, output_dir: str, project_name: str) -> str:
    """
    Compiles the complete Hindenburg session (.nhsx) XML file by combining Info,
    AudioPool, Tracks, Clipboard, Markers, Document, TextItems, NavPoints, and Config elements.
    
    Args:
        audio_data: List of dicts containing filename, absolute_path, and duration (in ms).
        metadata: Dict containing project metadata.
        output_dir: The target output directory where the .nhsx file will be written.
        project_name: The name of the project.
        
    Returns:
        The absolute path to the compiled .nhsx session file.
    """
    import datetime
    
    session = ET.Element("Session", {
        "Version": "Narrator Studio 1.60",
        "Samplerate": "44100",
        "Time": format_hindenburg_time(0.0)
    })
    
    # 1. Info node
    today_str = datetime.date.today().isoformat()
    info_attrs = {
        "Copyright": metadata.get("copyright", "Further reproduction or distribution in other than an accessible format is prohibited"),
        "Revision": metadata.get("revision", "0"),
        "Language": metadata.get("language", "en"),
        "MultimediaType": "audioNCX",
        "Title": metadata.get("title", project_name),
        "Producer": metadata.get("producer", "NLS Media Lab"),
        "RecordingAgency": metadata.get("recording_agency", "Zinio Inc."),
        "ProducedDate": metadata.get("produced_date", today_str),
        "SourceDate": metadata.get("source_date", today_str)
    }
    ET.SubElement(session, "Info", info_attrs)
    
    # 2. AudioPool node
    audio_pool = generate_audio_pool_node(audio_data, project_name, output_dir)
    session.append(audio_pool)
    
    # 3. Tracks node
    tracks = generate_tracks_node(audio_data)
    session.append(tracks)
    
    # 4. Clipboard node (boilerplate)
    clipboard = ET.SubElement(session, "Clipboard")
    ET.SubElement(clipboard, "Group", {"Caption": "Group 1"})
    ET.SubElement(clipboard, "Group", {"Caption": "Group 2"})
    ET.SubElement(clipboard, "Group", {"Caption": "Group 3"})
    ET.SubElement(clipboard, "Group", {"Caption": "Group 4"})
    
    # 5. Markers node (boilerplate)
    ET.SubElement(session, "Markers")
    
    # 6. Document link node
    xhtml_full_path = os.path.abspath(os.path.join(output_dir, f"{project_name} Files", "Document.xhtml"))
    ET.SubElement(session, "Document", {
        "File": "Document.xhtml",
        "DocPath": xhtml_full_path
    })
    
    # 7. TextItems node
    text_items = get_static_text_items()
    session.append(text_items)
    
    # 8. NavPoints node
    nav_points = generate_nav_points_node(audio_data)
    session.append(nav_points)
    
    # 9. Config node (boilerplate)
    config = ET.SubElement(session, "Config", {"Name": "Config"})
    book_export = ET.SubElement(config, "BookExport")
    ET.SubElement(book_export, "Z3986", {
        "SplitTime": "90", "AudioEncoding": "Mono", "SplitLevel": "1",
        "AudioFormat": "AMR-WBP", "WAVCopy": "0", "HeadingsFile": "0"
    })
    ET.SubElement(book_export, "Daisy2.02", {
        "AudioFormat": "MP3", "SplitLevel": "1", "AudioEncoding": "Low Quality"
    })
    ET.SubElement(book_export, "ePub3", {
        "AudioFormat": "MP3", "SplitLevel": "1", "AudioEncoding": "Low Quality"
    })
    
    # Write NHSX to target directory
    os.makedirs(output_dir, exist_ok=True)
    nhsx_filename = f"{project_name}.nhsx"
    nhsx_path = os.path.join(output_dir, nhsx_filename)
    
    tree = ET.ElementTree(session)
    ET.indent(tree, space="  ", level=0)
    with open(nhsx_path, "wb") as f:
        f.write(b'<?xml version="1.0" encoding="UTF-8"?>\n')
        tree.write(f, encoding="UTF-8", xml_declaration=False, method="xml")
    
    return nhsx_path






