import os

DAISY_BOILERPLATE_CSS = """/* This file was generated by HABC from style.css */
html { display: block; width: 100%; }
head, head * { display: none; }
body { display: block; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); font-family: arial, verdana, sans-serif; line-height: 1.5em; margin-top: 4em; margin-bottom: 2em; margin-left: 6em; margin-right: 6em; }
.frontmatter, .bodymatter, .rearmatter { display: block; margin-top: 1em; margin-bottom: 1em; }
.doctitle, .docauthor, .covertitle { display: block; font-weight: bold; text-align: center; }
.doctitle { font-size: 2.0em; }
.docauthor { font-style: italic; font-size: 1.5em; }
h1, h2, h3, h4, h5, h6, .levelhd { display: block; font-weight: bold; margin-bottom: 0.5em; }
h1 { font-size: 1.7em; margin-top: 0.8em; }
h2 { font-size: 1.5em; margin-top: 0.7em; }
h3 { font-size: 1.4em; margin-top: 0.6em; }
p { display: block; margin-top: 0.7em; }
.prodnote { display: block; padding: 0.2em; margin: 0.3em; border: 1px solid black; }
.pagenum { display: inline; padding: 0.2em 0.2em 0.2em 1em; border: 1px solid rgb(200, 200, 250); }
"""

def write_boilerplate_css(output_dir: str) -> str:
    """
    Writes the static DAISY/DTBook boilerplate CSS to the specified output directory.
    
    Args:
        output_dir: The target directory where style.css will be written.
        
    Returns:
        The absolute path to the generated style.css file.
    """
    os.makedirs(output_dir, exist_ok=True)
    css_path = os.path.join(output_dir, "style.css")
    with open(css_path, "w", encoding="utf-8") as f:
        f.write(DAISY_BOILERPLATE_CSS)
    return css_path


import xml.etree.ElementTree as ET

STATIC_TEXT_ITEMS_XML = """<TextItems>
  <TextItem Name="Title" State="1" Key="1">
    <h1 class="docTitle">Title</h1>
  </TextItem>
  <TextItem Name="Author" State="1" Key="2">
    <h1 class="docAuthor">Author(s)</h1>
  </TextItem>
  <TextItem Name="Annotation" State="1" Key="3">
    <h1 class="annotation">Library of Congress Annotation</h1>
  </TextItem>
  <TextItem Name="Close" State="1" Key="4">
    <h1 class="close">Close</h1>
  </TextItem>
  <TextItem Name="H1" State="1" Key="5">
    <h1>Header 1</h1>
  </TextItem>
  <TextItem Name="H2" State="1" Key="6">
    <h2>Header 2</h2>
  </TextItem>
  <TextItem Name="H3" State="1" Key="7">
    <h3>Header 3</h3>
  </TextItem>
  <TextItem Name="H4" Key="8">
    <h4>Header 4</h4>
  </TextItem>
  <TextItem Name="H5" Key="9">
    <h5>Header 5</h5>
  </TextItem>
  <TextItem Name="H6" Key="0">
    <h6>Header 6</h6>
  </TextItem>
  <TextItem Name="Reader's Note" State="1">
    <div class="prodnote">
      <p>Reader's Note</p>
    </div>
  </TextItem>
  <TextItem Name="Segment" State="1">
    <p class="segment">Segment</p>
  </TextItem>
  <TextItem Name="Note-Ref" State="1">
    <a class="noteref">*</a>
  </TextItem>
  <TextItem Name="Note-Content" State="1">
    <div class="note">
      <p>Note content</p>
    </div>
  </TextItem>
  <TextItem Name="Sidebar" State="1">
    <div class="sidebar">
      <p>Sidebar</p>
    </div>
  </TextItem>
  <TextItem Name="Page" State="1">
    <span class="pagenum">#</span>
  </TextItem>
  <TextItem Name="Line" State="0">
    <span class="linenum">#</span>
  </TextItem>
</TextItems>"""

def get_static_text_items() -> ET.Element:
    """
    Returns the static <TextItems> XML element tree block.
    
    Returns:
        An xml.etree.ElementTree.Element representing the root of the TextItems block.
    """
    return ET.fromstring(STATIC_TEXT_ITEMS_XML)


def format_duration_hhmmss_mmm(ms: float) -> str:
    """
    Converts duration in milliseconds to HH:MM:SS.mmm format.
    
    Args:
        ms: Duration in milliseconds.
        
    Returns:
        Formatted time string (HH:MM:SS.mmm).
    """
    total_seconds = int(ms // 1000)
    milliseconds = int(round(ms % 1000))
    if milliseconds >= 1000:
        total_seconds += 1
        milliseconds -= 1000
        
    hours = total_seconds // 3600
    minutes = (total_seconds // 60) % 60
    seconds = total_seconds % 60
    
    return f"{hours:02d}:{minutes:02d}:{seconds:02d}.{milliseconds:03d}"


def generate_audio_pool_node(audio_data: list[dict], project_name: str, output_dir: str) -> ET.Element:
    """
    Dynamically generates the <AudioPool> XML node for an .nhsx file.
    
    Args:
        audio_data: A list of dicts containing 'filename', 'absolute_path', and 'duration' (in ms).
        project_name: The name of the project.
        output_dir: The target output directory.
        
    Returns:
        An xml.etree.ElementTree.Element representing the <AudioPool> node.
    """
    audio_files_dir = os.path.join(output_dir, f"{project_name} Files")
    audio_pool = ET.Element("AudioPool", {
        "Path": f"{project_name} Files",
        "Location": audio_files_dir
    })
    
    for idx, item in enumerate(audio_data, start=1):
        filename = item["filename"]
        abs_path = item["absolute_path"]
        duration_ms = item["duration"]
        
        duration_str = format_duration_hhmmss_mmm(duration_ms)
        
        ET.SubElement(audio_pool, "File", {
            "Id": str(idx),
            "Name": filename,
            "OriginalPath": abs_path,
            "Duration": duration_str,
            "Leq": "-"
        })
        
    return audio_pool


