import os

DAISY_BOILERPLATE_CSS = """/* This file was generated by HABC from style.css */
html { display: block; width: 100%; }
head, head * { display: none; }
body { display: block; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); font-family: arial, verdana, sans-serif; line-height: 1.5em; margin-top: 4em; margin-bottom: 2em; margin-left: 6em; margin-right: 6em; }
.frontmatter, .bodymatter, .rearmatter { display: block; margin-top: 1em; margin-bottom: 1em; }
.doctitle, .docauthor, .covertitle { display: block; font-weight: bold; text-align: center; }
.doctitle { font-size: 2.0em; }
.docauthor { font-style: italic; font-size: 1.5em; }
h1, h2, h3, h4, h5, h6, .levelhd { display: block; font-weight: bold; margin-bottom: 0.5em; }
h1 { font-size: 1.7em; margin-top: 0.8em; }
h2 { font-size: 1.5em; margin-top: 0.7em; }
h3 { font-size: 1.4em; margin-top: 0.6em; }
p { display: block; margin-top: 0.7em; }
.prodnote { display: block; padding: 0.2em; margin: 0.3em; border: 1px solid black; }
.pagenum { display: inline; padding: 0.2em 0.2em 0.2em 1em; border: 1px solid rgb(200, 200, 250); }
"""

def write_boilerplate_css(output_dir: str) -> str:
    """
    Writes the static DAISY/DTBook boilerplate CSS to the specified output directory.
    
    Args:
        output_dir: The target directory where style.css will be written.
        
    Returns:
        The absolute path to the generated style.css file.
    """
    os.makedirs(output_dir, exist_ok=True)
    css_path = os.path.join(output_dir, "style.css")
    with open(css_path, "w", encoding="utf-8") as f:
        f.write(DAISY_BOILERPLATE_CSS)
    return css_path
